title: gerstenberg.clinic
email: (409) 210-3336
description: ""
baseurl: ""
url: "http://gerstenberg.clinic"
sameas: "http://www.facebook.com/gerstenberg.clinic"
keywords: "Dr. G, Dr G,Gerstenberg,Gertenberg,Gersteberg,Gerstenburg,Gurstenburg ,Gutenberg,Gutenburg ,Gurtenberg,Gurtenburg,Paul,Doctor,Dr,wellness,Primary care,physician,natural,family,family practice,holistic,Nederland,Port neches,Texas,Midcounty,jefferson county, Beaumont,South,East,School exam,Well woman,Exam,Checkup,Well visit,medicare,natural,PRP,rooster comb,knee pain,facial,filler,hair loss,knee replacement,p-shot,pshot,o-shot,oshot,biote,hormones, BHRT,"
description: "A Holistic Approach for the Whole Family. Gerstenberg.clinic offers primary medical care and also cutting-edge services such as: PRP therapy, O-shot®, P-shot®, homeopathic options, BioTE human-identical hormone therapy, medical weight management, PRP facial, PRP facelift, male ED treatments and more."
sass:
    style: compressed
plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
