title: gerstenberg.clinic
email: (409) 210-3336
description: ""
baseurl: ""
url: "http://gerstenberg.clinic"
keywords: "Gerstenberg,Gertenberg,Gersteberg,Gerstenburg,Gurstenburg ,Gutenberg,Gutenburg ,Gurtenberg,Gurtenburg ,Paul,Doctor,Dr,wellness,Primary care,physician,natural,family,family practice,holistic,Nederland,Port neches,Texas,Midcounty,Beaumont,South,East,School exam,Well woman,Exam,Checkup,Well visit,medicare"
description: "Gerstenberg.clinicWELLNESS provides cutting-edge products and services including: vitamins, homeopathic remedies, human-identical hormone therapy, medical weight management options, aesthetic treatments, male ED treatments and more. Gerstenberg.clinic offers primary care for all ages. This includes non-immunization newborn, infant and child checkups as well as school physicals, well-women exams and annual wellness visits for Medicare enrollees."
sass:
    style: compressed
plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
