title: gerstenberg.clinic
email: (409) 210-3336
description: ""
baseurl: ""
url: "http://gerstenberg.clinic"
sameas: "http://www.facebook.com/gerstenberg.clinic"
keywords: "thymosin, antibody testing, covid, coronavirus, igg, igm, Dr. G, Dr G,Gerstenberg,Gertenberg,Gersteberg,Gerstenburg,Gurstenburg ,Gutenberg,Gutenburg ,Gurtenberg,Gurtenburg ,Paul,Doctor,Dr,wellness,Primary care,physician,natural,family,family practice,holistic,Nederland,Port neches,Texas,Midcounty,Beaumont,South,East,School exam,Well woman,Exam,Checkup,Well visit,medicare,natural,PRP,rooster comb,knee pain,vampire,facial,filler,hair loss,knee replacement,p-shot,pshot,o-shot,oshot,biote,hormones, BHRT,"
description: "A Holistic Approach for the Whole Family. Gerstenberg.clinic offers primary medical care for all ages and also provides cutting-edge products and services through gerstenberg.cinicWELLNESS. This includes: homeopathic options, human-identical hormone therapy, medical weight management, aesthetic treatments, male ED treatments and more."
sass:
    style: compressed
plugins:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - CNAME
  - .gitignore
